name: opal

services:
  postgres_data:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=opal_data
      - POSTGRES_USER=opal_user
      - POSTGRES_PASSWORD=opal_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./roles.txt:/docker-entrypoint-initdb.d/data.json
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opal_user -d opal_data"]
      interval: 10s
      timeout: 5s
      retries: 5
  opal_server:
    image: permitio/opal-server:latest
    environment:
      - OPAL_POLICY_REPO_URL=https://github.com/ShivuPolicePatil/opal
      #- OPAL_POLICY_REPO_URL=git@github.com:HayGroup/kfone-keycloak-service.git
      #- OPAL_POLICY_REPO_MAIN_BRANCH=poc/opa-setup-in-kfone
      #- OPAL_POLICY_REPO_SSH_KEY=-----BEGIN OPENSSH PRIVATE KEY-----_b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW_QyNTUxOQAAACC8W6LZ5Z6yGppP008QL2n9rUoyadxKuHnD2IK5hzYPLgAAAKhhgYIcYYGC_HAAAAAtzc2gtZWQyNTUxOQAAACC8W6LZ5Z6yGppP008QL2n9rUoyadxKuHnD2IK5hzYPLg_AAAEAme53qlvKzDSYxgucKyQg6hgw8/Lw+J7IxpLt2JEB+irxbotnlnrIamk/TTxAvaf2t_SjJp3Eq4ecPYgrmHNg8uAAAAJHNoaXZ1a3VtYXIucG9saWNlcGF0aWxAa29ybmZlcnJ5Lm_NvbQE=_-----END OPENSSH PRIVATE KEY-----_
      #- POLICY_REPO_MANIFEST_PATH=opa/bundles
      - OPAL_POLICY_REPO_POLLING_INTERVAL=30
      - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"url":"postgresql://opal_user:opal_password@postgres_data:5432/opal_data","config":{"fetcher":"PostgresFetchProvider","query":"WITH role_data AS (SELECT role, json_object_agg(resource, scopes ORDER BY resource) as resource_scopes FROM roles GROUP BY role ORDER BY role) SELECT json_object_agg(role, resource_scopes ORDER BY role)::jsonb as roles FROM role_data;","connection_params":{"password":"opal_password"}},"topics":["policy_data"], "periodic_update_interval":10}]}}
      #- OPAL_DATA_CONFIG_SOURCES={"config": {"entries": [{"url": "postgresql://opal_user@postgres_data:5432/postgres","config": {"fetcher": "PostgresFetchProvider","query": "SELECT * from roles;","connection_params": {"password": "opal_password"}},"topics": ["policy_data"],"dst_path": "/"}]}}
      #- OPAL_LOG_FORMAT_INCLUDE_PID=true
      #- OPAL_POLICY_SUBSCRIPTION_DIRS=opa/bundles
    ports:
      - "7002:7002"
    depends_on:
      - postgres_data
  opal_client:
    #image: permitio/opal-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_INLINE_OPA_LOG_FORMAT=http
      - OPAL_FETCH_PROVIDER_MODULES=opal_common.fetcher.providers,opal_fetcher_postgres.provider
      #- OPAL_DATA_TOPICS=policy_data
      #- OPAL_DATA_UPDATER_ENABLED=true
      #- OPAL_DATA_UPDATER_INTERVAL=30
      #- OPAL_POLICY_SUBSCRIPTION_DIRS=data

      # Uncomment the following lines to enable storing & loading OPA data from a backup file:
      # - OPAL_OFFLINE_MODE_ENABLED=true
    # volumes:
    #  - opa_backup:/opal/backup:rw

    ports:
      - "7766:7000"
      - "8181:8181"
    depends_on:
      - opal_server
      - postgres_data
    command: sh -c "exec ./wait-for.sh opal_server:7002 --timeout=20 -- ./start.sh"

volumes:
  opa_backup:
  postgres_data:
